deepspeed  --master_port=9906  --include localhost:0,1,2,3  src/train_bash.py \
    --stage sft \
    --deepspeed ds_z3_config.json \
    --model_name_or_path llama2-7B \
    --do_train \
    --dataset gsm8k_rev\
    --bf16 True \
    --template default \
    --finetuning_type full \
    --lora_target q_proj,v_proj \
    --output_dir \
    --overwrite_cache \
    --overwrite_output_dir \
    --per_device_train_batch_size 4\
    --gradient_accumulation_steps 2\
    --warmup_ratio 0.08 \
    --lr_scheduler_type cosine \
    --logging_steps 2 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 3.0 \
    --plot_loss \
    --tf32 True  \
    > logllama2_7B.log 2>&1 & echo $! > run.pid
